---
title: "Sakura"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lubridate)
library(stringr)
```

Data from: http://atmenv.envi.osakafu-u.ac.jp/aono/kyophenotemp4/ via http://atmenv.envi.osakafu-u.ac.jp/aono/kyophenotemp4/.

```{r}
# Add styling information: 
width <- 10
title_font <- "Noto Sans Bold"
main_font <- "NotoSans"

theme_set(theme_minimal())
theme <- theme_update(
  text = element_text(family = main_font),
  plot.title = element_text(family = title_font, size = 18),
  plot.title.position = "plot",
  legend.position = "none",
  axis.title = element_text(size = 10),
  axis.text = element_text(size = 10),
  axis.title.x = element_text(family = main_font),
  axis.title.y = element_text(family = main_font),
  plot.caption = element_text(family = main_font, size = 8),
  plot.margin = margin(20,20,20,20)
  #plot.background = element_rect(fill = "#eceff4")
)

# Read in the data
sakura <- read.csv("sakura.csv", header = TRUE, sep=",", col.names = c("year", "dayOfYear", "rawDate", "sourceCode", "typeCode", "reference"))

# Turn rawDate and year into a date, calculate day of the year
sakura <- sakura %>% 
  mutate(date = make_date(year, str_sub(rawDate, 1,1), str_sub(rawDate, 2,3)), doy = yday(date))%>%
  mutate(bloom_date = as.Date(doy, origin = "2020-01-01"))
  
latest <- max(sakura$bloom_date, na.rm = TRUE)

sakura %>%
  ggplot(aes(year, bloom_date))+
  geom_point()+
  geom_smooth()+ 
  scale_y_date(labels = scales::label_date("%B %d"))+
  coord_cartesian(ylim = as.Date(c("2020-01-01", latest)), expand = TRUE) + 
  labs(
    title = "Sakura are blooming earlier",
    x = "Year",
    y = "Date of Full Flowering",
    caption = "Data: Aono and Kazui, 2008; Aono and Saito, 2010; Aono, 2012. http://atmenv.envi.osakafu-u.ac.jp/"
  ) + 
  ggsave("sakura-plot .png")
```


